parameters:
    module_systemMonitor:
            layout:
                title: "System Monitor"
                width: 600
                height: 300
                visible: false
                icon: "bundles/modulesystemmonitor/images/system.png"
                closable: true
                maximizable: true
                minimizable: true
                movable: true
                resizable: true
                defaultCloseOperation: 2
                position: 'center'
                showInTaskBar: true
                showDesktopIcon: true
                maximized: false